Add a swagger-plugin directive
SAP/swagger-plugin-for-sphinx pull request #187
Opened 2024-12-14 21:12 UTC by mikemckiernan

- Specify path to YAML in new directive.
- Rely on html_static_path extend to copy files.
- Put CSS and JS on pages with directive only.

Fixes https://github.com/SAP/swagger-plugin-for-sphinx/issues/186.

2024-12-30 20:57 UTC, kasium commented
Hi, sorry for the late reply. I'm currently on vacation but I try to get thru your code in the next time.

Your contribution is higly appreciated!

2024-12-30 21:19 UTC, mikemckiernan commented
> Hi, sorry for the late reply. I'm currently on vacation but I try to get thru your code in the next time.
> 
> Your contribution is higly appreciated!

Take your time--in the interim, I noticed that it's currently not possible to have more than one API specification on a page.  I'm planning to revise the JavaScript (not an expert!) to something like this, that does support more than one:

```
<div id="one"></div>
<div id="two"></div>
<script>
  window.onload = () => {
    window.ui = SwaggerUIBundle({
      url: "/documents/features/urls/1.yaml",
      dom_id: '#one',
    })
    window.ui = SwaggerUIBundle({
      url: "/documents/features/urls/2.yaml",
      dom_id: '#two',
    })
  }
</script>
```

2025-01-03 11:55 UTC, kasium requested changes
Only some nitpicks

2025-01-03 11:55 UTC, kasium commented on swagger_plugin_for_sphinx/_plugin.py
> +        # TODO: HTTP URLs
Can you please either resolve the TODO or provide more context?

2025-01-03 11:55 UTC, kasium commented on swagger_plugin_for_sphinx/_plugin.py
> +
Remove me

2025-01-03 12:01 UTC, kasium commented
I need to do some manual testing. Not sure if it makes sense to keep all three ways of configuration

2025-01-03 21:54 UTC, mikemckiernan commented on swagger_plugin_for_sphinx/_plugin.py
> +
What do you want removed?

2025-01-09 17:00 UTC, kasium commented on swagger_plugin_for_sphinx/_plugin.py
> +
sorry, I mean the empty line

2025-01-09 17:06 UTC, kasium commented on README.md
> +```
I think the RST example is enough

2025-01-09 17:06 UTC, kasium requested changes

2025-01-09 17:06 UTC, kasium commented on README.md
> +```
I think the RST example is enough

2025-01-09 17:17 UTC, kasium commented
Okay, I found some nitpicks about formatting and the docs. Please resolve them, then lets get this merged.

For my understanding. This directive does the same as the inline directive but no ``conf.py`` configuration is needed as well as automatic copy is enabled, right?

I think, three ways are two too much. Therefore I would later (after this is merged and released) do the following
* conf.py configuration is limited to specify the js, css, etc. files but no openapi spec anymore
* the inline directive is removed
* your added directive is the only one left: if the css/js files are not set, the `conf.py` ones are used (or the global defaults). The directive gets a new option `inline` which basically says if the spec is included as you programmed it, or if set to false, the _old_ behavior to render it as a full-page is used.

What do you think about this?

2025-01-10 13:25 UTC, merged

2025-01-10 13:26 UTC, kasium commented
@mikemckiernan merged; thanks a lot. If you have some time, feel free to check my comment above about the future of this project. I'll release a new version today

2025-01-10 13:26 UTC, mikemckiernan commented
> Okay, I found some nitpicks about formatting and the docs. Please resolve them, then lets get this merged.

Hopefully addressed.  If not, PLMK.

> For my understanding. This directive does the same as the inline directive but no `conf.py` configuration is needed as well as automatic copy is enabled, right?

Yes, that was my goal--to reduce the `conf.py` updates for page-level config and to add the CSS and JS only on pages that have the directive.  And yes, copy to whatever `html_static_path` is set to.

> I think, three ways are two too much. Therefore I would later (after this is merged and released) do the following
> 
> * conf.py configuration is limited to specify the js, css, etc. files but no openapi spec anymore
> * the inline directive is removed
> * your added directive is the only one left: if the css/js files are not set, the `conf.py` ones are used (or the global defaults). The directive gets a new option `inline` which basically says if the spec is included as you programmed it, or if set to false, the _old_ behavior to render it as a full-page is used.
> 
> What do you think about this?

I and my colleagues will use the new directive, but I was OK with keeping the existing approach.

2025-01-10 13:27 UTC, mikemckiernan commented
> @mikemckiernan merged; thanks a lot. If you have some time, feel free to check my comment above about the future of this project. I'll release a new version today

ACK.  Thanks a bunch!